[project]
name = "sublime-cracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nuitka>=2.7.12",
    "pyside6>=6.9.1",
]
